* quick start
1. in command prompt:
   #+begin_src sh
   git clone https://github.com/heartnheart/ewv.git
   cd ewv
   cargo install patch-crate
   cargo patch-crate
   cargo build
   emacs -Q -l local-test.el
   #+end_src
2. in emacs:
   =M-x ewv-browser-open-url= 输入网址如 =www.baidu.com=

* ewv-browser
1. =ewv-browser-open-url= 新 buffer 打开指定网页
2. =ewv-browser-open-file= 新 buffer 打开指定文件
3. =ewv-browser-open-history= 打开历史记录页面
4. =ewv-browser-history= 打开历史记录页面
5. =ewv-browser-open-session-in-edge= 关闭当前所有网页，然后在 msedge 中打开当前 session 中打开的网页。这个 msedge 会使用 =ewv-browser-user-data-folder= 定义的目录，从而与 ewv-browsedr 共享数据。可以在 edge 中进行一些处理（如安装、卸载、修改插件配置，修改书签历史记录等）。关闭 edge 后会重写在 emacs 中打开之前的网页。
6. =ewv-browser-pin-url= 和 =ewv-browser-unpin-url= pin/unpin 当前 url 到缓存文件中，之后可以使用 =ewv-browser-reopen-all-pinned-url= 重新打开之前 pin 过的 url. 可以放在 =emacs-start-up-hook= 中
8. 焦点在 emacs 的的时候目前定制了 4 个 key （这里应该写个 major mode）
   1. =i= 切换焦点到 webview
   2. =t= 切换 webview 的显示
   3. =e= 当前 buffer 加载新 url
   4. =f= 当前 buffer 加载新文件
9. 焦点在 webview 中
   1. =C-g= 切换焦点到 emacs
   2. =C-x= 切换焦点到 emacs 并输入 =C-x=
   3. =M-x= 切换焦点到 emacs 并输入 =M-x=
10. 代理
    1. 可以通过设置环境变量 =WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS= 配置代理。注意不要使用 emacs 的 =setenv= 函数，对 dynamic module 无效。比如可以在 command prompt 中执行
       #+begin_src sh
       set WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS="--proxy-server=127.0.0.1:7897"
       #+end_src
    2. 也可以使用 ZeroOmega 插件。


* todo-list
1. [ ] rust 回调 elisp 代码的异步消息机制需要改为 =open_channel= 需要 patch =emacs-module-rs=
2. [ ] 更好的分发机制，melpa?
3. =ewv-browser=
4. [ ] =ewv-mode-line=
5. [ ] =ewv-org-inline=
6. [ ] =ewv-popup=
